// Phone-size browser smoke test. Run against a preview server:
//   npm run build && npx vite preview --port 4173 &   then   node e2e/smoke.cjs
// Env: PW_MODULE (playwright path), CHROMIUM_PATH, APP_URL. The clock is pinned to 18 Oct 2026 so figures are deterministic.
const { chromium } = require(process.env.PW_MODULE || 'playwright')
const path = require('path')
const S = process.argv[2] || require('os').tmpdir()
const URL = process.env.APP_URL || 'http://localhost:4173/expense-tracker-/'
const FIXTURE = path.join(__dirname, 'fixture-backup.json')

let failed = 0
const ok = (c, m) => { if (c) console.log('✓', m); else { console.log('✗ FAIL:', m); failed++ } }

;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium' })
  const ctx = await browser.newContext({ viewport: { width: 390, height: 800 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
  await ctx.clock.setFixedTime(new Date(2026, 9, 18, 12, 0, 0))
  const page = await ctx.newPage()
  const errors = []
  page.on('pageerror', (e) => errors.push(e.message))
  page.on('console', (m) => m.type() === 'error' && errors.push(`${m.text()} @ ${m.location().url}`))
  page.on('dialog', (d) => d.accept())

  const body = (sel) => page.innerText(sel).catch(() => '')
  const expectText = async (sel, re, msg) => {
    try {
      await page.waitForFunction(([s, src, fl]) => new RegExp(src, fl).test(document.querySelector(s)?.innerText || ''), [sel, re.source, re.flags], { timeout: 4000 })
      ok(true, msg)
    } catch {
      ok(false, `${msg} — got: ${(await body(sel)).slice(0, 240).replace(/\n/g, ' ')}`)
    }
  }
  const noOverflow = async (where) => {
    const [sw, iw] = await page.evaluate(() => [document.documentElement.scrollWidth, innerWidth])
    ok(sw <= iw, `no horizontal overflow on ${where} (${sw} <= ${iw})`)
  }
  const tab = (name) => page.click(`nav .nav-item:has-text("${name}")`)
  const closed = () => page.waitForSelector('.sheet', { state: 'detached' })

  await page.goto(URL)
  await page.waitForSelector('.hero')

  // --- empty state ---
  await expectText('.hero', /Spent this month/i, 'fresh install: Home asks for budgets instead of showing a daily amount')

  // --- load the design's sample month through the real backup importer ---
  await page.click('button[aria-label^="Settings"]')
  await page.click('.row-card:has-text("Backup")')
  await page.setInputFiles('input[type=file]', FIXTURE)
  await expectText('[role=status]', /restored/, 'sample month imported')
  await page.click('button:has-text("Back")')
  await page.click('button:has-text("Back")')
  await page.reload()
  await page.waitForSelector('.hero')

  // --- Home: safe to spend, pace, forecast ---
  await expectText('.hero', /Safe to spend today[\s\S]*৳1,182[\s\S]*per day for the next 13 days/i, 'hero: safe to spend ৳1,182/day for 13 days')
  await expectText('.hero', /৳15,360 left/, 'hero: ৳15,360 left')
  await expectText('.hero', /Day 18 of 31/, 'hero: day 18 of 31')
  await expectText('.hero', /6 points ahead of pace\.[\s\S]*৳4,602 over budget/, 'hero: 6 points ahead of pace, forecast ৳4,602 over')
  await expectText('.trio', /Income[\s\S]*৳62,000[\s\S]*Spent[\s\S]*৳27,640[\s\S]*Kept[\s\S]*৳34,360/i, 'income / spent / kept totals')
  await expectText('main', /Food is ৳1,100 over its budget/, 'action: Food over budget')
  await expectText('main', /Keeping it near ৳450 a day/, 'action: recommends a ৳450/day cap')
  await expectText('main', /Transport has ৳900 left for 13 days/, 'action: Transport running low')
  await expectText('main', /That's ৳69 a day\. By this day last month you had spent ৳4,100/, 'action: per-day figure and last-month comparison')
  await expectText('main', /Internet ৳800 is due on 20 Oct/, 'action: upcoming recurring bill')
  await expectText('main', /108% of budget/, 'breakdown: Food at 108% of budget')
  await expectText('main', /▲ 26%/, 'breakdown: Food up 26% vs last month')
  await noOverflow('Home')
  await page.screenshot({ path: `${S}/home.png`, fullPage: true })

  // --- action -> History preset ---
  await page.click('button:has-text("See food entries")')
  await expectText('.trio', /Entries[\s\S]*11[\s\S]*Spent[\s\S]*৳15,100/i, 'History preset: 11 food entries in October worth ৳15,100')
  await page.fill('input[type=search]', 'Shwapno')
  await expectText('.trio', /Entries[\s\S]*1\b/i, 'History search narrows to 1 entry')
  await page.fill('input[type=search]', '')
  await noOverflow('History')
  await page.screenshot({ path: `${S}/history.png`, fullPage: true })

  // --- Insights ---
  await tab('Insights')
  await expectText('main', /Forecast for October[\s\S]*৳47,602/i, 'insights: forecast ৳47,602')
  await expectText('main', /vs budget ৳43,000[\s\S]*▲ ৳4,602 over/i, 'insights: ৳4,602 over budget')
  await expectText('main', /vs September ৳41,300[\s\S]*▲ 15% more/i, 'insights: 15% more than September')
  ok((await page.locator('svg.chart[role=img]').count()) === 1, 'insights: forecast chart rendered')
  await expectText('[aria-label="What if"]', /Food cap · ৳450\/day[\s\S]*Now ৳839\/day[\s\S]*৳42,547/, 'what-if: defaults to the recommended ৳450 cap, month ends at ৳42,547')
  await page.locator('input[type=range]').fill('400')
  await expectText('[aria-label="What if"]', /Food cap · ৳400\/day[\s\S]*৳41,897/, 'what-if: ৳400/day cap -> ৳41,897')
  await expectText('main', /23%[\s\S]*projected for the month/, 'insights: projected savings rate 23%')
  await expectText('main', /৳1,536[\s\S]*▲ 12% vs September \(৳1,377\)/, 'insights: daily average vs September')
  await expectText('main', /৳6,000[\s\S]*recurring, ৳800 still to come/, 'insights: fixed costs with upcoming')
  await expectText('[aria-label="What changed"]', /Food alone rose ৳3,100, more than the whole increase/, 'insights: Food drove the increase')
  await expectText('[aria-label="Costliest days"]', /Fridays|Saturdays|Sundays|Mondays|Tuesdays|Wednesdays|Thursdays/, 'insights: costliest weekday')
  await expectText('[aria-label="Biggest entries"]', /Rent[\s\S]*৳5,200/, 'insights: biggest entries lists rent')
  await noOverflow('Insights')
  await page.screenshot({ path: `${S}/insights.png`, fullPage: true })

  // --- Budgets: overage + suggestion to move budget ---
  await tab('Budgets')
  await expectText('main', /Over by ৳1,100/, 'budgets: Food over by ৳1,100')
  await expectText('main', /Shopping has ৳5,900 unused[\s\S]*Move ৳1,100 to Food/, 'budgets: suggests moving ৳1,100 from Shopping')
  await expectText('main', /৳1,182\/day available/, 'budgets: daily allowance chip')
  await noOverflow('Budgets')
  await page.screenshot({ path: `${S}/budgets.png`, fullPage: true })
  await page.click('button:has-text("Move ৳1,100")')
  await page.waitForFunction(() => !/Over by/.test(document.querySelector('main').innerText))
  ok(true, 'budgets: moving budget clears the overage')
  await expectText('main', /৳15,100 a month/, 'budgets: Food budget raised to ৳15,100')
  await tab('Home')
  await page.waitForFunction(() => !/over its budget/.test(document.querySelector('main').innerText))
  ok(true, 'home: over-budget action is gone after the move')

  // --- Add entry with the keypad; impact preview; save ---
  await page.click('button[aria-label="Add entry"]')
  for (const k of ['1', '2', '5', '0']) await page.click(`.keypad button[aria-label="${k}"]`)
  await expectText('.amount', /1,250/, 'keypad: amount shows 1,250')
  await page.click('.keypad button[aria-label="Delete last digit"]')
  await expectText('.amount', /\b125\b/, 'keypad: backspace')
  await page.click('.keypad button[aria-label="0"]')
  await page.click('.sheet .chip:has-text("Transport")')
  await expectText('.sheet .impact', /Transport would be ৳350 over budget[\s\S]*Total budget left/, 'impact: previews the budget effect before saving')
  await page.fill('input[aria-label=Note]', '').catch(() => {})
  await page.click('button:has-text("Add note")')
  await page.fill('input[aria-label=Note]', 'Airport ride')
  await noOverflow('Add entry sheet')
  await page.screenshot({ path: `${S}/add.png` })
  await page.click('button:has-text("Save expense")')
  await closed()
  await expectText('.hero', /৳28,890/, 'saving updates the hero (spent ৳28,890)')
  await expectText('main', /Airport ride/, 'new entry is in Recent')

  // edit -> delete
  await page.click('.row-card:has-text("Airport ride")')
  await expectText('.sheet', /Save changes/, 'edit sheet opens')
  await page.click('.sheet button:has-text("Delete")')
  await closed()
  await expectText('.hero', /৳27,640/, 'deleting restores the total')

  // repeat chips offer recent entries
  await page.click('button[aria-label="Add entry"]')
  await page.waitForSelector('.repeat .chip', { timeout: 4000 }).catch(() => {})
  ok((await page.locator('.repeat .chip').count()) >= 1, 'add sheet offers recent entries to repeat')
  await page.click('button[aria-label="Close"]')
  await closed()

  // income entry
  await page.click('button[aria-label="Add entry"]')
  await page.click('.seg button:has-text("Income")')
  for (const k of ['5', '0', '0', '0']) await page.click(`.keypad button[aria-label="${k}"]`)
  await expectText('.sheet', /Save income · ৳5,000/, 'income entry button states the amount')
  await page.click('button:has-text("Save income")')
  await closed()
  await expectText('.trio', /৳67,000/, 'income entry raises income to ৳67,000')

  // --- custom category with a drawn icon ---
  await page.click('button[aria-label^="Settings"]')
  await page.click('.row-card:has-text("Categories")')
  await page.click('button:has-text("+ Add")')
  await page.fill('input[aria-label=Name]', 'Coffee')
  await page.click('.icon-grid button[aria-label="coffee"]')
  await page.click('button:has-text("Save")')
  await closed()
  await expectText('main', /Coffee/, 'custom category created')
  ok((await page.locator('main .row-card:has-text("Coffee") svg').count()) === 1, 'custom category shows its drawn icon')
  await page.click('button:has-text("Back")')
  await page.click('button:has-text("Back")')

  // --- subcategories: manage, pick on an entry, see usage in detail ---
  const idb = (store) => page.evaluate((st) => new Promise((res, rej) => {
    const r = indexedDB.open('expense-tracker')
    r.onsuccess = () => { const q = r.result.transaction(st).objectStore(st).getAll(); q.onsuccess = () => res(q.result); q.onerror = () => rej(q.error) }
    r.onerror = () => rej(r.error)
  }), store)
  const openSettingsCategories = async () => { await page.click('button[aria-label^="Settings"]'); await page.click('.row-card:has-text("Categories")') }
  const backToHome = async () => { await page.click('button:has-text("Back")'); await page.click('button:has-text("Back")') }

  await openSettingsCategories()
  await expectText('main', /Bills[\s\S]*Electricity, Gas, Phone, Rent/, 'categories list shows the subcategories under Bills')
  await page.click('.row-card[aria-label="Edit Bills"]')
  await page.waitForSelector('[aria-label="Subcategories"] input[aria-label^="Rename"]')
  ok((await page.locator('[aria-label="Subcategories"] input[aria-label^="Rename"]').count()) === 4, 'Bills sheet lists its 4 subcategories')
  await page.fill('input[aria-label="New subcategory"]', 'Water')
  await page.click('[aria-label="Subcategories"] button:has-text("Add")')
  await page.waitForSelector('input[aria-label="Rename Water"]')
  await page.fill('input[aria-label="Rename Water"]', 'Water supply')
  await page.press('input[aria-label="Rename Water"]', 'Enter')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await page.click('.row-card[aria-label="Edit Bills"]')
  await page.waitForSelector('[aria-label="Subcategories"] input[aria-label^="Rename"]')
  ok((await page.locator('input[aria-label="Rename Water supply"]').count()) === 1, 'a subcategory can be added and renamed')
  await page.click('button[aria-label="Delete Water supply"]')
  await page.waitForFunction(() => !document.querySelector('input[aria-label="Rename Water supply"]'))
  ok(true, 'a subcategory can be deleted')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await backToHome()

  await page.click('button[aria-label="Add entry"]')
  for (const k of ['1', '8', '0', '0']) await page.click(`.keypad button[aria-label="${k}"]`)
  await page.click('.sheet .chip:has-text("Bills")')
  await page.waitForSelector('.sheet [aria-label="Subcategory"]')
  ok((await page.locator('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")').count()) === 1, 'entry sheet offers the category\'s subcategories')
  await page.click('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")')
  ok((await page.getAttribute('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")', 'aria-pressed')) === 'true', 'subcategory selected')
  await page.click('.sheet .chip:has-text("Food")')
  ok((await page.locator('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")').count()) === 0, 'switching category hides the other category\'s subcategories')
  await page.click('.sheet .chip:has-text("Bills")')
  ok((await page.getAttribute('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")', 'aria-pressed')) === 'false', 'subcategory is cleared after switching category')
  await page.click('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")')
  await page.click('button:has-text("Save expense")')
  await closed()
  await expectText('main', /Electricity[\s\S]*Bills › Electricity/, 'entry shows "Bills › Electricity"')

  await page.click('button[aria-label="Bills in detail"]')
  await expectText('.sheet', /Bills · October/, 'category detail opens for Bills')
  await expectText('.sheet', /Spent[\s\S]*৳7,400/i, 'detail: Bills total ৳7,400')
  await expectText('.sheet', /▲ 25% vs September \(same days\)/, 'detail: total vs September same days')
  await expectText('.sheet', /Rent[\s\S]*৳5,200[\s\S]*Electricity[\s\S]*৳1,800[\s\S]*Phone[\s\S]*৳400/, 'detail: subcategories ranked by amount')
  await expectText('.sheet', /Electricity[\s\S]*1 entry[\s\S]*24%[\s\S]*▲ 100%/, 'detail: Electricity share and change vs September')
  await expectText('[aria-label="Six month trend"]', /৳9k[\s\S]*৳7\.4k/, 'detail: six-month trend (September ৳9k, October ৳7.4k)')
  await expectText('[aria-label="Six month trend"]', /avg ৳1,800/, 'detail: average of the earlier months')
  await page.click('.sheet button.line-row:has-text("Electricity")')
  await expectText('[aria-label="Six month trend"]', /৳900[\s\S]*৳1\.8k/, 'detail: trend narrows to Electricity')
  await noOverflow('category detail sheet')
  await page.screenshot({ path: `${S}/detail.png` })
  await page.click('.sheet button:has-text("See entries")')
  await expectText('.trio', /Entries[\s\S]*1\b[\s\S]*Spent[\s\S]*৳1,800/i, 'See entries opens History filtered to Electricity')
  ok((await page.locator('select[aria-label="Subcategory"]').count()) === 1, 'History offers a subcategory filter for the chosen category')
  await tab('Home')

  // deleting a subcategory keeps the entries; deleting a category removes its subcategories
  await openSettingsCategories()
  await page.click('.row-card[aria-label="Edit Bills"]')
  await page.click('button[aria-label="Delete Electricity"]')
  await page.waitForFunction(() => !document.querySelector('input[aria-label="Rename Electricity"]'))
  let txs = await idb('transactions')
  ok(txs.every((t) => t.subcategoryId !== 3) && txs.filter((t) => t.categoryId === 3).length === 6, 'deleting a subcategory unlabels its entries but keeps them in the category')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await page.click('button:has-text("+ Add")')
  await page.fill('input[aria-label=Name]', 'Travel')
  await page.click('.icon-grid button[aria-label="plane"]')
  await page.click('.sheet button:has-text("Save")')
  await closed()
  await page.click('.row-card[aria-label="Edit Travel"]')
  await page.fill('input[aria-label="New subcategory"]', 'Flights')
  await page.click('[aria-label="Subcategories"] button:has-text("Add")')
  await page.waitForSelector('input[aria-label="Rename Flights"]')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await backToHome()
  await page.click('button[aria-label="Add entry"]')
  for (const k of ['5', '0', '0']) await page.click(`.keypad button[aria-label="${k}"]`)
  await page.click('.sheet .chip:has-text("Travel")')
  await page.click('.sheet [aria-label="Subcategory"] .chip:has-text("Flights")')
  await page.click('button:has-text("Save expense")')
  await closed()
  txs = await idb('transactions')
  const flightTx = txs.find((t) => t.amount === 50000 && t.subcategoryId != null)
  ok(!!flightTx, 'entry saved with its subcategory')
  await openSettingsCategories()
  await page.click('.row-card[aria-label="Edit Travel"]')
  await page.click('.sheet button:has-text("Delete")')
  await closed()
  const cats = await idb('categories')
  const subsLeft = await idb('subcategories')
  txs = await idb('transactions')
  const moved = txs.find((t) => t.id === flightTx.id)
  const otherId = cats.find((c) => c.kind === 'expense' && c.system).id
  ok(!cats.some((c) => c.name === 'Travel') && !subsLeft.some((x) => x.name === 'Flights'), 'deleting a category deletes its subcategories')
  ok(moved && moved.categoryId === otherId && moved.subcategoryId === undefined, 'its entries move to Other without the old subcategory label')
  await backToHome()

  // an older backup (no subcategories at all) still imports; stray labels are dropped
  const legacy = JSON.parse(require('fs').readFileSync(FIXTURE, 'utf8'))
  delete legacy.subcategories
  const legacyPath = path.join(S, 'fixture-legacy.json')
  require('fs').writeFileSync(legacyPath, JSON.stringify(legacy))
  await page.click('button[aria-label^="Settings"]')
  await page.click('.row-card:has-text("Backup")')
  await page.setInputFiles('input[type=file]', legacyPath)
  await expectText('[role=status]', /restored/, 'older backup without subcategories imports')
  txs = await idb('transactions')
  ok((await idb('subcategories')).length === 0 && txs.every((t) => t.subcategoryId == null) && txs.length > 20, 'dangling subcategory labels are dropped on import')
  await page.click('button:has-text("Back")')
  await page.click('button:has-text("Back")')
  await page.click('button[aria-label="Previous month"]')
  await page.click('button[aria-label="Next month"]')

  // --- past month view ---
  await page.click('button[aria-label="Previous month"]')
  await expectText('.hero', /Spent in September[\s\S]*৳41,300[\s\S]*of ৳43,000 budget/i, 'previous month: summary of September')
  await noOverflow('Home (previous month)')
  await page.click('button[aria-label^="September"]') // label button jumps back to this month
  await expectText('.hero', /Safe to spend today/i, 'label button returns to this month')

  // --- theme setting: System / Light / Dark ---
  const themeState = () => page.evaluate(() => ({ attr: document.documentElement.dataset.theme, bg: getComputedStyle(document.body).backgroundColor, saved: localStorage.getItem('expense-tracker-theme') }))
  const LIGHT_BG = 'rgb(244, 244, 241)'
  const DARK_BG = 'rgb(11, 15, 23)'
  await page.click('button[aria-label^="Settings"]')
  await expectText('[aria-label="Appearance"]', /System[\s\S]*Light[\s\S]*Dark/, 'settings: Appearance offers System / Light / Dark')
  let t = await themeState()
  ok(t.attr === 'light' && t.bg === LIGHT_BG, `system follows a light phone (${t.attr}, ${t.bg})`)
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark')
  t = await themeState()
  ok(t.bg === DARK_BG, `system switches live when the phone goes dark (${t.bg})`)
  await page.click('[aria-label="Appearance"] button:has-text("Light")')
  t = await themeState()
  ok(t.attr === 'light' && t.bg === LIGHT_BG && t.saved === 'light', 'choosing Light overrides a dark phone and is saved')
  await page.reload()
  await page.waitForSelector('.nav')
  t = await themeState()
  ok(t.attr === 'light' && t.bg === LIGHT_BG, 'Light persists after reload (even though the phone is dark)')
  await page.emulateMedia({ colorScheme: 'light' })
  await page.click('button[aria-label^="Settings"]')
  await page.click('[aria-label="Appearance"] button:has-text("Dark")')
  t = await themeState()
  ok(t.attr === 'dark' && t.bg === DARK_BG && t.saved === 'dark', 'choosing Dark overrides a light phone and is saved')
  await noOverflow('Settings (dark)')
  await page.screenshot({ path: `${S}/settings-dark.png` })
  await page.reload()
  await page.waitForSelector('.nav')
  t = await themeState()
  ok(t.attr === 'dark' && t.bg === DARK_BG, 'Dark persists after reload')
  await page.click('button[aria-label^="Settings"]')
  await page.click('[aria-label="Appearance"] button:has-text("System")')
  t = await themeState()
  ok(t.attr === 'light' && t.saved === 'system', 'back to System follows the (light) phone again')
  await page.click('button:has-text("Back")')

  // --- dark mode ---
  const dark = await browser.newContext({ viewport: { width: 390, height: 800 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: 'dark' })
  await dark.clock.setFixedTime(new Date(2026, 9, 18, 12, 0, 0))
  const dp = await dark.newPage()
  dp.on('dialog', (d) => d.accept())
  await dp.goto(URL)
  await dp.click('button[aria-label^="Settings"]')
  await dp.click('.row-card:has-text("Backup")')
  await dp.setInputFiles('input[type=file]', FIXTURE)
  await dp.waitForSelector('[role=status]')
  await dp.click('button:has-text("Back")')
  await dp.click('button:has-text("Back")')
  await dp.waitForSelector('.hero')
  await dp.screenshot({ path: `${S}/home-dark.png`, fullPage: true })
  await dp.click('nav .nav-item:has-text("Insights")')
  await dp.waitForSelector('svg.chart')
  await dp.screenshot({ path: `${S}/insights-dark.png`, fullPage: true })
  ok(true, 'dark mode renders (screenshots saved)')
  await dark.close()

  // --- offline, with bundled fonts ---
  await page.reload()
  await page.waitForSelector('.hero')
  await page.waitForTimeout(1500)
  await ctx.setOffline(true)
  await page.reload()
  await page.waitForSelector('.hero')
  ok((await page.locator('nav').count()) === 1, 'app loads offline')
  const fonts = await page.evaluate(async () => { await document.fonts.ready; return [...document.fonts].filter((f) => f.status === 'loaded').map((f) => f.family) })
  ok(fonts.some((f) => /Figtree/.test(f)) && fonts.some((f) => /Bricolage/.test(f)), `bundled fonts load offline (${[...new Set(fonts)].join(', ')})`)

  ok(errors.length === 0, `no console/page errors ${JSON.stringify(errors)}`)
  await browser.close()
  process.exit(failed ? 1 : 0)
})().catch((e) => { console.log('✗ CRASH', e.message); process.exit(1) })
