// Phone-size browser smoke test. Run against a preview server:
//   npm run build && npx vite preview --port 4173 &   then   node e2e/smoke.cjs
// Env: PW_MODULE (playwright path), CHROMIUM_PATH, APP_URL. The clock is pinned to 18 Oct 2026 so figures are deterministic.
const { chromium } = require(process.env.PW_MODULE || 'playwright')
const path = require('path')
const S = process.argv[2] || require('os').tmpdir()
const URL = process.env.APP_URL || 'http://localhost:4173/expense-tracker-/'
const FIXTURE = path.join(__dirname, 'fixture-backup.json')

let failed = 0
const ok = (c, m) => { if (c) console.log('✓', m); else { console.log('✗ FAIL:', m); failed++ } }

;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium' })
  const ctx = await browser.newContext({ viewport: { width: 390, height: 800 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
  await ctx.clock.setFixedTime(new Date(2026, 9, 18, 12, 0, 0))
  const page = await ctx.newPage()
  const errors = []
  page.on('pageerror', (e) => errors.push(e.message))
  page.on('console', (m) => m.type() === 'error' && errors.push(`${m.text()} @ ${m.location().url}`))
  page.on('dialog', (d) => d.accept())

  const body = (sel) => page.innerText(sel).catch(() => '')
  const expectText = async (sel, re, msg) => {
    try {
      await page.waitForFunction(([s, src, fl]) => new RegExp(src, fl).test(document.querySelector(s)?.innerText || ''), [sel, re.source, re.flags], { timeout: 4000 })
      ok(true, msg)
    } catch {
      ok(false, `${msg} — got: ${(await body(sel)).slice(0, 240).replace(/\n/g, ' ')}`)
    }
  }
  const noOverflow = async (where) => {
    const [sw, iw] = await page.evaluate(() => [document.documentElement.scrollWidth, innerWidth])
    ok(sw <= iw, `no horizontal overflow on ${where} (${sw} <= ${iw})`)
  }
  const color = (sel) => page.locator(sel).first().evaluate((el) => getComputedStyle(el).color)
  const GREEN = 'rgb(21, 128, 61)'
  const RED = 'rgb(185, 28, 28)'
  const tab = (name) => page.click(`nav .nav-item:has-text("${name}")`)
  const closed = () => page.waitForSelector('.sheet', { state: 'detached' })
  const palette = () => page.waitForSelector('.palette')
  const openSearch = async () => { await page.click('button[aria-label="Search the app"]'); await palette() }
  const typeQuery = async (q) => { await page.fill('.palette input', q); await page.waitForTimeout(60) }
  const firstResult = () => page.locator('.palette [role=option]').first().innerText()

  await page.goto(URL)
  await page.waitForSelector('.hero')

  // --- empty state ---
  await expectText('.hero', /Spent this month/i, 'fresh install: Home asks for budgets instead of showing a daily amount')
  ok(!/Nothing needs attention|Every budget is on pace/.test(await body('main')), 'fresh install: no misleading "on track" message before any budget exists')

  // --- load the design's sample month through the real backup importer ---
  await page.click('button[aria-label^="Settings"]')
  await page.click('.row-card:has-text("Backup")')
  await page.setInputFiles('input[type=file]', FIXTURE)
  await expectText('[role=status]', /restored/, 'sample month imported')
  await page.click('button:has-text("Back")')
  await page.click('button:has-text("Back")')
  await page.reload()
  await page.waitForSelector('.hero')

  // --- Home: safe to spend, pace, forecast ---
  await expectText('.hero', /Safe to spend today[\s\S]*৳1,182[\s\S]*per day for the next 13 days/i, 'hero: safe to spend ৳1,182/day for 13 days')
  await expectText('.hero', /৳15,360 left/, 'hero: ৳15,360 left')
  await expectText('.hero', /Day 18 of 31/, 'hero: day 18 of 31')
  await expectText('.hero', /6 points ahead of pace\.[\s\S]*৳4,602 over budget/, 'hero: 6 points ahead of pace, forecast ৳4,602 over')
  await expectText('.trio', /Income[\s\S]*৳62,000[\s\S]*Spent[\s\S]*৳27,640[\s\S]*Kept[\s\S]*৳34,360/i, 'income / spent / kept totals')
  ok((await color('.trio .stat:has-text("Income") .money-in')) === GREEN, 'Home: Income total is green')
  ok((await color('.trio .stat:has-text("Spent") .money-out')) === RED, 'Home: Spent total is red')
  ok((await color('main .row-card .amt')) === RED && /^−/.test(await page.locator('main .row-card .amt').first().innerText()), 'Home: expense entries are red with a − sign')
  await expectText('main', /Food is ৳1,100 over its budget/, 'action: Food over budget')
  await expectText('main', /Keeping it near ৳450 a day/, 'action: recommends a ৳450/day cap')
  await expectText('main', /Transport has ৳900 left for 13 days/, 'action: Transport running low')
  await expectText('main', /That's ৳69 a day\. By this day last month you had spent ৳4,100/, 'action: per-day figure and last-month comparison')
  await expectText('main', /Internet ৳800 is due on 20 Oct/, 'action: upcoming recurring bill')
  await expectText('main', /108% of budget/, 'breakdown: Food at 108% of budget')
  await expectText('main', /▲ 26%/, 'breakdown: Food up 26% vs last month')
  await noOverflow('Home')
  await page.screenshot({ path: `${S}/home.png`, fullPage: true })

  // --- action -> History preset ---
  await page.click('button:has-text("See food entries")')
  await expectText('.trio', /Entries[\s\S]*11[\s\S]*Spent[\s\S]*৳15,100/i, 'History preset: 11 food entries in October worth ৳15,100')
  await page.fill('input[type=search]', 'Shwapno')
  await expectText('.trio', /Entries[\s\S]*1\b/i, 'History search narrows to 1 entry')
  await page.click('[aria-label="Filters"] button:has-text("All")')
  await page.fill('input[type=search]', 'Freelance')
  await page.waitForSelector('.row-card:has-text("Freelance payment")')
  ok((await color('.row-card:has-text("Freelance payment") .amt')) === GREEN && /^\+/.test(await page.locator('.row-card:has-text("Freelance payment") .amt').innerText()), 'History: income entry is green with a + sign')
  ok((await color('.day-head:has-text("Thu 15 Oct") span')) === GREEN, 'History: a day with net income is green')
  await page.fill('input[type=search]', 'Rickshaw')
  await page.waitForSelector('.row-card:has-text("Rickshaw")')
  ok((await color('.row-card:has-text("Rickshaw") .amt')) === RED, 'History: expense entry is red')
  ok((await color('.day-head span')) === RED, 'History: a day with net spending is red')
  await expectText('.trio', /Spent[\s\S]*৳120/i, 'History: totals follow the search')
  ok((await color('.trio .stat:has-text("Spent") .money-out')) === RED && (await color('.trio .stat:has-text("Income") .money-in')) === GREEN, 'History: Spent red, Income green')
  await page.fill('input[type=search]', '')
  await noOverflow('History')
  await page.screenshot({ path: `${S}/history.png`, fullPage: true })

  // --- Insights ---
  await tab('Insights')
  await expectText('main', /Forecast for October[\s\S]*৳47,602/i, 'insights: forecast ৳47,602')
  await expectText('main', /vs budget ৳43,000[\s\S]*▲ ৳4,602 over/i, 'insights: ৳4,602 over budget')
  await expectText('main', /vs September ৳41,300[\s\S]*▲ 15% more/i, 'insights: 15% more than September')
  ok((await page.locator('svg.chart[role=img]').count()) === 1, 'insights: forecast chart rendered')
  await expectText('[aria-label="What if"]', /Food cap · ৳450\/day[\s\S]*Now ৳839\/day[\s\S]*৳42,547/, 'what-if: defaults to the recommended ৳450 cap, month ends at ৳42,547')
  await page.locator('input[type=range]').fill('400')
  await expectText('[aria-label="What if"]', /Food cap · ৳400\/day[\s\S]*৳41,897/, 'what-if: ৳400/day cap -> ৳41,897')
  await expectText('main', /23%[\s\S]*projected for the month/, 'insights: projected savings rate 23%')
  await expectText('main', /৳1,536[\s\S]*▲ 12% vs September \(৳1,377\)/, 'insights: daily average vs September')
  await expectText('main', /৳6,000[\s\S]*recurring, ৳800 still to come/, 'insights: fixed costs with upcoming')
  await expectText('[aria-label="What changed"]', /Food alone rose ৳3,100, more than the whole increase/, 'insights: Food drove the increase')
  await expectText('[aria-label="Costliest days"]', /Fridays|Saturdays|Sundays|Mondays|Tuesdays|Wednesdays|Thursdays/, 'insights: costliest weekday')
  await expectText('[aria-label="Biggest entries"]', /Rent[\s\S]*৳5,200/, 'insights: biggest entries lists rent')
  await noOverflow('Insights')
  await page.screenshot({ path: `${S}/insights.png`, fullPage: true })

  // --- Budgets: overage + suggestion to move budget ---
  await tab('Plan')
  await expectText('main', /Over by ৳1,100/, 'budgets: Food over by ৳1,100')
  await expectText('main', /Shopping has ৳5,900 unused[\s\S]*Move ৳1,100 to Food/, 'budgets: suggests moving ৳1,100 from Shopping')
  await expectText('main', /৳1,182\/day available/, 'budgets: daily allowance chip')
  await noOverflow('Budgets')
  await page.screenshot({ path: `${S}/budgets.png`, fullPage: true })
  await page.click('button:has-text("Move ৳1,100")')
  await page.waitForFunction(() => !/Over by/.test(document.querySelector('main').innerText))
  ok(true, 'budgets: moving budget clears the overage')
  await expectText('main', /৳15,100 a month/, 'budgets: Food budget raised to ৳15,100')
  await tab('Home')
  await page.waitForFunction(() => !/over its budget/.test(document.querySelector('main').innerText))
  ok(true, 'home: over-budget action is gone after the move')

  // --- Savings: monthly goal, plans (DPS / Sanchay Patra / goal), deposits, month report ---
  const taka = (n) => '৳' + new Intl.NumberFormat('en-BD', { maximumFractionDigits: 0 }).format(n)
  const inOrder = (text, parts) => { const t = text.toLowerCase(); let at = 0; for (const p of parts) { const i = t.indexOf(p.toLowerCase(), at); if (i < 0) return p; at = i + p.length } return null } // labels are CSS-uppercased, so compare ignoring case
  const expectInOrder = async (sel, parts, msg) => {
    const t = await body(sel)
    const missing = inOrder(t, parts)
    ok(missing === null, missing === null ? msg : `${msg} — missing "${missing}" in: ${t.slice(0, 400).replace(/\n/g, ' | ')}`)
  }
  await tab('Home')
  await expectText('[aria-label="Savings this month"]', /Savings · October[\s\S]*৳8,000[\s\S]*of ৳10,000 goal[\s\S]*৳2,000 to go[\s\S]*Kept ৳34,360/i, 'savings (Home): card shows saved vs goal and what is kept')
  await expectText('main', /Put ৳2,000 aside to reach your savings goal/, 'savings (Home): "do this next" says how much to put aside')
  await expectText('main', /Goal ৳10,000, saved ৳8,000 so far\. You have ৳34,360 left this month\./, 'savings (Home): ...with the numbers behind it')
  await page.click('[aria-label="Savings this month"]')
  await page.waitForSelector('[aria-label="Savings plans"]')
  ok((await page.getAttribute('.seg button:has-text("Savings")', 'aria-pressed')) === 'true', 'savings: the Home card opens Plan > Savings')
  await expectText('[aria-label="Savings this month"]', /Saved in October[\s\S]*৳8,000[\s\S]*of ৳10,000 goal · 13% of income[\s\S]*৳2,000 to go\. You have ৳34,360 kept this month\.[\s\S]*Earned[\s\S]*৳62,000[\s\S]*Spent[\s\S]*৳27,640[\s\S]*Kept[\s\S]*৳34,360/i, 'savings: this month — saved vs goal, earned, spent, kept')
  const cards = (await body('[aria-label="Savings plans"]'))
  await expectInOrder('[aria-label="Savings plans"]', ['City Bank DPS', 'DPS · 3 years · 9.5%', 'Paid this month', `${taka(50000)} of ${taka(180000)}`, 'Matures 10 Jan 2029', `Expected at maturity about ${taka(205850)}`], 'savings: DPS card (progress, maturity date, expected payout after 10% tax)')
  await expectInOrder('[aria-label="Savings plans"]', ['Paribar Sanchay Patra', 'One-time deposit · 5 years · 11.28%', 'Earning', `${taka(200000)} of ${taka(200000)}`, 'Matures 1 Dec 2030', `Profit about ${taka(1692)} a month after tax`], 'savings: Sanchay Patra card (monthly profit after tax)')
  await expectInOrder('[aria-label="Savings plans"]', ['Emergency fund', 'Savings goal · 2 years', 'Paid this month', `${taka(23000)} of ${taka(120000)}`, 'By 1 Jun 2028', `Save ${taka(5000)} a month to reach it`], 'savings: goal card')
  await expectInOrder('[aria-label="Plans total"]', ['Plans commit each month', taka(10000), 'Fully covered', 'Deposited so far', taka(273000), 'Expected back at maturity', taka(627370)], 'savings: totals (committed, covered, deposited, expected back)')
  await expectInOrder('[aria-label="Last six months"]', ['October', taka(8000), 'of ৳10,000', 'Earned ৳62,000 · Spent ৳27,640 · Saved 13%', 'September', taka(10000), 'Met', 'Saved 16%'], 'savings: last six months, newest first, with goal met flags')
  await noOverflow('Savings')
  await page.screenshot({ path: `${S}/savings.png`, fullPage: true })

  // monthly report
  await page.click('button[aria-label="October report"]')
  await expectText('.sheet', /October 2026 report[\s\S]*You earned ৳62,000, spent ৳27,640 \(45% of income\) and saved ৳8,000 \(13%\)\./, 'report: one-line summary')
  await expectInOrder('.sheet', ['Savings goal', taka(8000), 'of ৳10,000', '৳2,000 to go'], 'report: goal progress')
  await expectInOrder('.sheet', ['Kept (earned − spent)', taka(34360), 'Moved into savings plans', taka(8000), 'Left in hand', taka(26360)], 'report: kept vs saved vs left in hand')
  await expectText('.sheet', /Budget ৳43,000: spent ৳27,640 \(64%\)/, 'report: budget summary')
  await expectText('.sheet', /Food[\s\S]*৳15,100[\s\S]*55% of spending · 24% of income/, 'report: spending by category with share of income')
  await expectText('.sheet', /Where it came from[\s\S]*Salary[\s\S]*৳55,000[\s\S]*Business[\s\S]*৳7,000/i, 'report: income by category')
  await noOverflow('month report sheet')
  await page.screenshot({ path: `${S}/report.png` })
  await page.click('.sheet button[aria-label="Close"]')
  await closed()

  // plan detail + recording and removing a deposit
  await page.click('[aria-label^="City Bank DPS"]')
  await expectInOrder('.sheet', ['City Bank DPS', 'DPS · 3 years · 9.5%', 'Paid this month', 'You deposit in total', taka(180000), 'Interest after tax', taka(25850), 'Expected at maturity', taka(205850), 'Matures on', '10 Jan 2029', 'Deposits (10)'], 'plan detail: progress, payout estimate, deposits')
  ok((await page.inputValue('input[aria-label="Deposit amount"]')) === '5000', 'plan detail: the deposit amount is pre-filled with the installment')
  await page.screenshot({ path: `${S}/plan-detail.png` })
  await page.click('button:has-text("Record deposit")')
  await expectText('.sheet', /Recorded ✓[\s\S]*Deposits \(11\)/i, 'plan detail: recording a deposit adds it')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await expectText('[aria-label="Savings this month"]', /৳13,000[\s\S]*Goal reached ✓/, 'savings: the extra deposit pushes this month over the goal')
  await page.click('[aria-label^="City Bank DPS"]')
  await page.click('.sheet button[aria-label*="18 Oct"]')
  await expectText('.sheet', /Deposits \(10\)/i, 'plan detail: a deposit can be removed')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await expectText('[aria-label="Savings this month"]', /৳8,000[\s\S]*of ৳10,000 goal/, 'savings: back to ৳8,000 after removing it')

  // the monthly goal: fixed amount or share of income
  await page.click('button:has-text("Edit goal")')
  await page.click('.sheet .seg button:has-text("% of income")')
  await page.fill('input[aria-label="Percent of income"]', '20')
  await expectText('.sheet', /About ৳12,400 on the income you have recorded/, 'goal: a percentage turns into an amount from this month\'s income')
  await page.click('button:has-text("Save goal")')
  await closed()
  await expectText('[aria-label="Savings this month"]', /of ৳12,400 goal/, 'goal: 20% of ৳62,000 = ৳12,400')
  await page.click('button:has-text("Edit goal")')
  await page.click('.sheet .seg button:has-text("Fixed amount")')
  await page.fill('input[aria-label="Monthly savings goal"]', '10000')
  await page.click('button:has-text("Save goal")')
  await closed()
  await expectText('[aria-label="Savings this month"]', /of ৳10,000 goal/, 'goal: back to a fixed ৳10,000')

  // new plans: live estimates for each type
  await page.click('button:has-text("New savings plan")')
  const saveBtn = page.locator('.sheet button:has-text("Save plan")')
  await page.fill('input[aria-label="Plan name"]', 'Test DPS')
  await page.fill('#plan-amount', '1000')
  ok(await saveBtn.isDisabled(), 'new plan: cannot be saved without an interest rate (nothing is pre-filled)')
  await page.click('.sheet .chip:has-text("1 yr")')
  await page.fill('#plan-rate', '8')
  await page.fill('#plan-tax', '0')
  await expectText('[aria-label="Estimate"]', /You deposit ৳12,000 over 12 months\. Interest after tax is about ৳529, so you get about ৳12,529 on/, 'new DPS: live estimate (৳1,000 x 12 at 8%)')
  ok(await saveBtn.isEnabled(), 'new plan: can be saved once complete')
  await page.click('.sheet .seg button:has-text("Sanchay / FDR")')
  await page.fill('#plan-amount', '100000')
  await page.click('.sheet .chip:has-text("5 yrs")')
  await page.fill('#plan-rate', '10')
  await page.fill('#plan-tax', '10')
  await expectText('[aria-label="Estimate"]', new RegExp(`About ${taka(750)} a month after tax \\(${taka(45000)} in total\\), and your ${taka(100000)} comes back on`), 'new Sanchay Patra: monthly profit after tax')
  await page.click('.sheet .seg button:has-text("Quarterly")')
  await expectText('[aria-label="Estimate"]', /About ৳2,250 every 3 months after tax \(৳45,000 in total\)/, 'new Sanchay Patra: quarterly profit')
  await page.click('.sheet .seg button:has-text("At maturity")')
  await expectText('[aria-label="Estimate"]', new RegExp(`Profit after tax is about ${taka(57475)}, so you get about ${taka(157475)} on`), 'new Sanchay Patra: profit compounded to maturity')
  await page.click('.sheet .seg button:has-text("Goal")')
  await page.fill('#plan-amount', '120000')
  await page.click('.sheet .chip:has-text("2 yrs")')
  await page.fill('#plan-rate', '')
  await page.fill('input[aria-label="Plan name"]', 'Test goal')
  await expectText('[aria-label="Estimate"]', new RegExp(`Save ${taka(5000)} a month for 24 months to reach ${taka(120000)} by`), 'new goal: monthly saving needed')
  await noOverflow('plan form')
  await page.screenshot({ path: `${S}/plan-form.png` })
  await saveBtn.click()
  await closed()
  await page.waitForSelector('[aria-label^="Test goal"]')
  ok((await page.locator('[aria-label="Savings plans"] [role=button]').count()) === 4, 'new plan: appears in the list')
  await page.click('[aria-label^="Test goal"]')
  await page.click('.sheet button:has-text("Edit plan")')
  await page.click('.sheet button:has-text("Delete")')
  await closed()
  await page.waitForFunction(() => document.querySelectorAll('[aria-label="Savings plans"] [role=button]').length === 3)
  ok(true, 'plan: can be edited and deleted (with its deposits)')

  // savings are findable, and the Plan tab remembers where you were
  for (const [q, expectTitle] of [['dps', 'Savings'], ['sanchay patra', 'Savings'], ['savings goal', 'Savings'], ['monthly report', 'Monthly report']]) {
    await openSearch()
    await typeQuery(q)
    ok(new RegExp(`^${expectTitle}`).test(await firstResult()), `search: "${q}" finds ${expectTitle}`)
    await page.click('button[aria-label="Close search"]')
    await page.waitForSelector('.palette', { state: 'detached' })
  }
  await openSearch()
  await typeQuery('monthly report')
  await page.press('.palette input', 'Enter')
  await expectText('.sheet', /October 2026 report/, 'search: "Monthly report" opens the report')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await tab('Home')
  await tab('Plan')
  ok((await page.getAttribute('.seg button:has-text("Savings")', 'aria-pressed')) === 'true', 'Plan tab remembers Savings when you come back')
  await page.click('.seg button:has-text("Budgets")')
  await tab('Home')

  // --- Add entry with the keypad; impact preview; save ---
  await page.click('button[aria-label="Add entry"]')
  for (const k of ['1', '2', '5', '0']) await page.click(`.keypad button[aria-label="${k}"]`)
  await expectText('.amount', /1,250/, 'keypad: amount shows 1,250')
  await page.click('.keypad button[aria-label="Delete last digit"]')
  await expectText('.amount', /\b125\b/, 'keypad: backspace')
  await page.click('.keypad button[aria-label="0"]')
  await page.click('.sheet .chip:has-text("Transport")')
  await expectText('.sheet .impact', /Transport would be ৳350 over budget[\s\S]*Total budget left/, 'impact: previews the budget effect before saving')
  await page.fill('input[aria-label=Note]', '').catch(() => {})
  await page.click('button:has-text("Add note")')
  await page.fill('input[aria-label=Note]', 'Airport ride')
  await noOverflow('Add entry sheet')
  await page.screenshot({ path: `${S}/add.png` })
  await page.click('button:has-text("Save expense")')
  await closed()
  await expectText('.hero', /৳28,890/, 'saving updates the hero (spent ৳28,890)')
  await expectText('main', /Airport ride/, 'new entry is in Recent')

  // edit -> delete
  await page.click('.row-card:has-text("Airport ride")')
  await expectText('.sheet', /Save changes/, 'edit sheet opens')
  await page.click('.sheet button:has-text("Delete")')
  await closed()
  await expectText('.hero', /৳27,640/, 'deleting restores the total')

  // repeat chips offer recent entries
  await page.click('button[aria-label="Add entry"]')
  await page.waitForSelector('.repeat .chip', { timeout: 4000 }).catch(() => {})
  ok((await page.locator('.repeat .chip').count()) >= 1, 'add sheet offers recent entries to repeat')
  await page.click('button[aria-label="Close"]')
  await closed()

  // income entry
  await page.click('button[aria-label="Add entry"]')
  await page.click('.seg button:has-text("Income")')
  for (const k of ['5', '0', '0', '0']) await page.click(`.keypad button[aria-label="${k}"]`)
  await expectText('.sheet', /Save income · ৳5,000/, 'income entry button states the amount')
  await page.click('button:has-text("Save income")')
  await closed()
  await expectText('.trio', /৳67,000/, 'income entry raises income to ৳67,000')

  // --- custom category with a drawn icon ---
  await page.click('button[aria-label^="Settings"]')
  await page.click('.row-card:has-text("Categories")')
  await page.click('button:has-text("New expense category")')
  await page.fill('input[aria-label=Name]', 'Coffee')
  await page.click('.icon-grid button[aria-label="coffee"]')
  await page.click('button:has-text("Save")')
  await closed()
  await expectText('main', /Coffee/, 'custom category created')
  ok((await page.locator('main .row-card:has-text("Coffee") svg').count()) === 1, 'custom category shows its drawn icon')
  await page.click('button:has-text("Back")')
  await page.click('button:has-text("Back")')

  // --- top bar: search + gear aligned on every screen ---
  const aligned = async (where) => {
    const a = await page.locator('.topbar .searchbtn').boundingBox()
    const g = await page.locator('.topbar .icon-btn').boundingBox()
    const ok1 = a && g && Math.abs((a.y + a.height / 2) - (g.y + g.height / 2)) <= 1 && Math.abs(a.height - g.height) <= 1 && a.x + a.width < g.x
    ok(!!ok1, `${where}: search bar and gear share one row (same height, same centre line)`)
  }
  for (const name of ['Home', 'History', 'Insights', 'Plan']) {
    await tab(name)
    ok((await page.locator('.topbar').count()) === 1, `${name}: top bar present`)
    await aligned(name)
  }
  await tab('Home')

  // --- smart search ---
  await openSearch()
  await expectText('.palette', /Quick actions[\s\S]*Add expense[\s\S]*Add income/i, 'search: empty query offers quick actions')
  await noOverflow('search panel')
  await typeQuery('backap')
  ok(/Backup & restore/.test(await firstResult()), 'search: tolerates a typo ("backap" -> Backup & restore)')
  await page.press('.palette input', 'Enter')
  await expectText('main', /Backup[\s\S]*Export/, 'search: Enter jumps straight to Settings > Backup')
  await page.click('button:has-text("Back")')
  await page.click('button:has-text("Back")')
  await openSearch()
  await typeQuery('forcast')
  ok(/Forecast/.test(await firstResult()), 'search: finds Insights sections ("forcast" -> Forecast)')
  await page.press('.palette input', 'Enter')
  await expectText('main', /Insights/, 'search: opens Insights at that section')
  await openSearch()
  await typeQuery('export')
  ok(/Backup & restore/.test(await firstResult()), 'search: understands synonyms ("export" -> Backup & restore)')
  await typeQuery('night')
  ok(/Dark theme/.test(await firstResult()), 'search: understands synonyms ("night" -> Dark theme)')
  await page.press('.palette input', 'Enter')
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark')
  ok(true, 'search: "Dark theme" switches the theme directly')
  await openSearch()
  await typeQuery('theme')
  await page.press('.palette input', 'ArrowDown')
  await page.press('.palette input', 'Enter')
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'light')
  ok(true, 'search: arrow keys + Enter pick the second result (Light theme)')
  await openSearch()
  await typeQuery('gas')
  await expectText('.palette', /Gas[\s\S]*Bills › subcategory/, 'search: finds subcategories with their parent')
  await page.press('.palette input', 'Enter')
  await expectText('.trio', /Entries[\s\S]*1\b/i, 'search: a subcategory result opens History filtered to it')
  await openSearch()
  await typeQuery('food')
  await expectText('.palette', /Food[\s\S]*Expense category/, 'search: finds categories')
  await page.press('.palette input', 'Enter')
  await expectText('.sheet', /Food · October/, 'search: an expense category opens its detail sheet')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await openSearch()
  await typeQuery('freelance')
  await page.click('.palette [role=option]:has-text("Search entries for")')
  await page.waitForSelector('.row-card:has-text("Freelance payment")')
  ok((await page.inputValue('input[type=search]')) === 'Freelance' || (await page.inputValue('input[type=search]')) === 'freelance', 'search: falls back to searching entries by text')
  await openSearch()
  await typeQuery('zzzzqq')
  await expectText('.palette', /No matching screen or setting[\s\S]*Search entries for/i, 'search: says so when nothing matches, and still offers an entry search')
  await page.press('.palette input', 'Escape')
  await page.waitForSelector('.palette', { state: 'detached' })
  ok(true, 'search: Escape closes the panel')
  await openSearch()
  await page.click('button[aria-label="Close search"]')
  await page.waitForSelector('.palette', { state: 'detached' })
  await openSearch()
  await typeQuery('system theme')
  await page.press('.palette input', 'Enter')
  await tab('Home')

  // --- Categories: Expense / Income tabs and a button that is always at the top ---
  await page.click('button[aria-label^="Settings"]')
  await aligned('Settings')
  await page.click('.row-card:has-text("Categories")')
  await expectText('main', /Expense \(\d+\)[\s\S]*Income \(\d+\)/, 'categories: Expense / Income tabs with counts')
  const addBox = await page.locator('button:has-text("New expense category")').boundingBox()
  ok(addBox && addBox.y < 330, `categories: the add button is at the top of the screen (y=${addBox && Math.round(addBox.y)})`)
  ok(!/Salary/.test(await body('main')), 'categories: the expense tab does not list income categories')
  await page.click('.seg button:has-text("Income")')
  await expectText('main', /Salary[\s\S]*Business[\s\S]*Gift/, 'categories: the Income tab lists income categories')
  await page.click('button:has-text("New income category")')
  ok((await page.getAttribute('.sheet .seg button:has-text("Income")', 'aria-pressed')) === 'true', 'categories: a new category opens on the tab you were viewing (Income)')
  await page.fill('input[aria-label=Name]', 'Side gig')
  await page.click('.sheet button:has-text("Save")')
  await closed()
  await expectText('main', /Side gig/, 'categories: the new income category appears in the Income list')
  await (async () => { await page.click('button:has-text("Back")'); await page.click('button:has-text("Back")') })()

  // --- subcategories: manage, pick on an entry, see usage in detail ---
  const idb = (store) => page.evaluate((st) => new Promise((res, rej) => {
    const r = indexedDB.open('expense-tracker')
    r.onsuccess = () => { const q = r.result.transaction(st).objectStore(st).getAll(); q.onsuccess = () => res(q.result); q.onerror = () => rej(q.error) }
    r.onerror = () => rej(r.error)
  }), store)
  const openSettingsCategories = async () => { await page.click('button[aria-label^="Settings"]'); await page.click('.row-card:has-text("Categories")') }
  const backToHome = async () => { await page.click('button:has-text("Back")'); await page.click('button:has-text("Back")') }

  await openSettingsCategories()
  await expectText('main', /Bills[\s\S]*Electricity, Gas, Phone, Rent/, 'categories list shows the subcategories under Bills')
  await page.click('.row-card[aria-label="Edit Bills"]')
  await page.waitForSelector('[aria-label="Subcategories"] input[aria-label^="Rename"]')
  ok((await page.locator('[aria-label="Subcategories"] input[aria-label^="Rename"]').count()) === 4, 'Bills sheet lists its 4 subcategories')
  await page.fill('input[aria-label="New subcategory"]', 'Water')
  await page.click('[aria-label="Subcategories"] button:has-text("Add")')
  await page.waitForSelector('input[aria-label="Rename Water"]')
  await page.fill('input[aria-label="Rename Water"]', 'Water supply')
  await page.press('input[aria-label="Rename Water"]', 'Enter')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await page.click('.row-card[aria-label="Edit Bills"]')
  await page.waitForSelector('[aria-label="Subcategories"] input[aria-label^="Rename"]')
  ok((await page.locator('input[aria-label="Rename Water supply"]').count()) === 1, 'a subcategory can be added and renamed')
  await page.click('button[aria-label="Delete Water supply"]')
  await page.waitForFunction(() => !document.querySelector('input[aria-label="Rename Water supply"]'))
  ok(true, 'a subcategory can be deleted')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await backToHome()

  await page.click('button[aria-label="Add entry"]')
  for (const k of ['1', '8', '0', '0']) await page.click(`.keypad button[aria-label="${k}"]`)
  await page.click('.sheet .chip:has-text("Bills")')
  await page.waitForSelector('.sheet [aria-label="Subcategory"]')
  ok((await page.locator('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")').count()) === 1, 'entry sheet offers the category\'s subcategories')
  await page.click('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")')
  ok((await page.getAttribute('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")', 'aria-pressed')) === 'true', 'subcategory selected')
  await page.click('.sheet .chip:has-text("Food")')
  ok((await page.locator('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")').count()) === 0, 'switching category hides the other category\'s subcategories')
  await page.click('.sheet .chip:has-text("Bills")')
  ok((await page.getAttribute('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")', 'aria-pressed')) === 'false', 'subcategory is cleared after switching category')
  await page.click('.sheet [aria-label="Subcategory"] .chip:has-text("Electricity")')
  await page.click('button:has-text("Save expense")')
  await closed()
  await expectText('main', /Electricity[\s\S]*Bills › Electricity/, 'entry shows "Bills › Electricity"')

  await page.click('button[aria-label="Bills in detail"]')
  await expectText('.sheet', /Bills · October/, 'category detail opens for Bills')
  await expectText('.sheet', /Spent[\s\S]*৳7,400/i, 'detail: Bills total ৳7,400')
  await expectText('.sheet', /▲ 25% vs September \(same days\)/, 'detail: total vs September same days')
  await expectText('.sheet', /Rent[\s\S]*৳5,200[\s\S]*Electricity[\s\S]*৳1,800[\s\S]*Phone[\s\S]*৳400/, 'detail: subcategories ranked by amount')
  await expectText('.sheet', /Electricity[\s\S]*1 entry[\s\S]*24%[\s\S]*▲ 100%/, 'detail: Electricity share and change vs September')
  await expectText('[aria-label="Six month trend"]', /৳9k[\s\S]*৳7\.4k/, 'detail: six-month trend (September ৳9k, October ৳7.4k)')
  await expectText('[aria-label="Six month trend"]', /avg ৳1,800/, 'detail: average of the earlier months')
  await page.click('.sheet button.line-row:has-text("Electricity")')
  await expectText('[aria-label="Six month trend"]', /৳900[\s\S]*৳1\.8k/, 'detail: trend narrows to Electricity')
  await noOverflow('category detail sheet')
  await page.screenshot({ path: `${S}/detail.png` })
  await page.click('.sheet button:has-text("See entries")')
  await expectText('.trio', /Entries[\s\S]*1\b[\s\S]*Spent[\s\S]*৳1,800/i, 'See entries opens History filtered to Electricity')
  await page.waitForSelector('select[aria-label="Subcategory"]', { timeout: 4000 }).catch(() => {})
  ok((await page.locator('select[aria-label="Subcategory"]').count()) === 1, 'History offers a subcategory filter for the chosen category')
  await tab('Home')

  // deleting a subcategory keeps the entries; deleting a category removes its subcategories
  await openSettingsCategories()
  await page.click('.row-card[aria-label="Edit Bills"]')
  await page.click('button[aria-label="Delete Electricity"]')
  await page.waitForFunction(() => !document.querySelector('input[aria-label="Rename Electricity"]'))
  let txs = await idb('transactions')
  ok(txs.every((t) => t.subcategoryId !== 3) && txs.filter((t) => t.categoryId === 3).length === 6, 'deleting a subcategory unlabels its entries but keeps them in the category')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await page.click('button:has-text("New expense category")')
  await page.fill('input[aria-label=Name]', 'Travel')
  await page.click('.icon-grid button[aria-label="plane"]')
  await page.click('.sheet button:has-text("Save")')
  await closed()
  await page.click('.row-card[aria-label="Edit Travel"]')
  await page.fill('input[aria-label="New subcategory"]', 'Flights')
  await page.click('[aria-label="Subcategories"] button:has-text("Add")')
  await page.waitForSelector('input[aria-label="Rename Flights"]')
  await page.click('.sheet button[aria-label="Close"]')
  await closed()
  await backToHome()
  await page.click('button[aria-label="Add entry"]')
  for (const k of ['5', '0', '0']) await page.click(`.keypad button[aria-label="${k}"]`)
  await page.click('.sheet .chip:has-text("Travel")')
  await page.click('.sheet [aria-label="Subcategory"] .chip:has-text("Flights")')
  await page.click('button:has-text("Save expense")')
  await closed()
  txs = await idb('transactions')
  const flightTx = txs.find((t) => t.amount === 50000 && t.subcategoryId != null)
  ok(!!flightTx, 'entry saved with its subcategory')
  await openSettingsCategories()
  await page.click('.row-card[aria-label="Edit Travel"]')
  await page.click('.sheet button:has-text("Delete")')
  await closed()
  const cats = await idb('categories')
  const subsLeft = await idb('subcategories')
  txs = await idb('transactions')
  const moved = txs.find((t) => t.id === flightTx.id)
  const otherId = cats.find((c) => c.kind === 'expense' && c.system).id
  ok(!cats.some((c) => c.name === 'Travel') && !subsLeft.some((x) => x.name === 'Flights'), 'deleting a category deletes its subcategories')
  ok(moved && moved.categoryId === otherId && moved.subcategoryId === undefined, 'its entries move to Other without the old subcategory label')
  await backToHome()

  // an older backup (no subcategories at all) still imports; stray labels are dropped
  const legacy = JSON.parse(require('fs').readFileSync(FIXTURE, 'utf8'))
  delete legacy.subcategories
  const legacyPath = path.join(S, 'fixture-legacy.json')
  require('fs').writeFileSync(legacyPath, JSON.stringify(legacy))
  await page.click('button[aria-label^="Settings"]')
  await page.click('.row-card:has-text("Backup")')
  await page.setInputFiles('input[type=file]', legacyPath)
  await expectText('[role=status]', /restored/, 'older backup without subcategories imports')
  txs = await idb('transactions')
  ok((await idb('subcategories')).length === 0 && txs.every((t) => t.subcategoryId == null) && txs.length > 20, 'dangling subcategory labels are dropped on import')
  await page.click('button:has-text("Back")')
  await page.click('button:has-text("Back")')
  await page.click('button[aria-label="Previous month"]')
  await page.click('button[aria-label="Next month"]')

  // backups carry savings; a backup from before savings existed still imports
  await page.click('button[aria-label^="Settings"]')
  await page.click('.row-card:has-text("Backup")')
  const [dl2] = await Promise.all([page.waitForEvent('download'), page.click('button:has-text("Export")')])
  const exportPath = path.join(S, 'export-savings.json')
  await dl2.saveAs(exportPath)
  const exported = JSON.parse(require('fs').readFileSync(exportPath, 'utf8'))
  ok(exported.version === 4 && exported.plans.length === 3 && exported.deposits.length === 16 && exported.settings.some((x) => x.key === 'savingsTarget'), `backup: export includes savings plans, deposits and the goal (${exported.plans.length} plans, ${exported.deposits.length} deposits)`)
  const bare = JSON.parse(require('fs').readFileSync(FIXTURE, 'utf8'))
  delete bare.plans; delete bare.deposits; delete bare.settings
  const barePath = path.join(S, 'fixture-no-savings.json')
  require('fs').writeFileSync(barePath, JSON.stringify(bare))
  await page.setInputFiles('input[type=file]', barePath)
  await expectText('[role=status]', /restored/, 'backup: a file from before savings existed imports')
  ok((await idb('plans')).length === 0 && (await idb('deposits')).length === 0 && (await idb('settings')).length === 0, 'backup: import replaces savings data too (an older file has none)')
  await page.click('button:has-text("Back")')
  await page.click('button:has-text("Back")')
  await expectText('main', /Set a monthly savings goal, or add a DPS or Sanchay Patra plan/, 'savings (Home): invites you to start when there is no goal or plan')
  await tab('Plan')
  await page.click('.seg button:has-text("Savings")')
  await expectText('main', /No plans yet\. Add a DPS, a Sanchay Patra or a savings goal/, 'savings: friendly empty state')
  await expectText('main', /Set a monthly savings goal to see how close you are each month/, 'savings: prompts for a goal')
  await tab('Home')
  // restore the full sample month for what follows
  await page.click('button[aria-label^="Settings"]')
  await page.click('.row-card:has-text("Backup")')
  await page.setInputFiles('input[type=file]', exportPath)
  await expectText('[role=status]', /restored/, 'backup: the export restores savings plans again')
  ok((await idb('plans')).length === 3 && (await idb('deposits')).length === 16, 'backup: round trip keeps 3 plans and 16 deposits')
  await page.click('button:has-text("Back")')
  await page.click('button:has-text("Back")')

  // --- past month view ---
  await page.click('button[aria-label="Previous month"]')
  await expectText('.hero', /Spent in September[\s\S]*৳41,300[\s\S]*of ৳43,000 budget/i, 'previous month: summary of September')
  await noOverflow('Home (previous month)')
  await page.click('button[aria-label^="September"]') // label button jumps back to this month
  await expectText('.hero', /Safe to spend today/i, 'label button returns to this month')

  // --- theme setting: System / Light / Dark ---
  const themeState = () => page.evaluate(() => ({ attr: document.documentElement.dataset.theme, bg: getComputedStyle(document.body).backgroundColor, saved: localStorage.getItem('expense-tracker-theme') }))
  const LIGHT_BG = 'rgb(244, 244, 241)'
  const DARK_BG = 'rgb(11, 15, 23)'
  await page.click('button[aria-label^="Settings"]')
  await expectText('[aria-label="Appearance"]', /System[\s\S]*Light[\s\S]*Dark/, 'settings: Appearance offers System / Light / Dark')
  let t = await themeState()
  ok(t.attr === 'light' && t.bg === LIGHT_BG, `system follows a light phone (${t.attr}, ${t.bg})`)
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark')
  t = await themeState()
  ok(t.bg === DARK_BG, `system switches live when the phone goes dark (${t.bg})`)
  await page.click('[aria-label="Appearance"] button:has-text("Light")')
  t = await themeState()
  ok(t.attr === 'light' && t.bg === LIGHT_BG && t.saved === 'light', 'choosing Light overrides a dark phone and is saved')
  await page.reload()
  await page.waitForSelector('.nav')
  t = await themeState()
  ok(t.attr === 'light' && t.bg === LIGHT_BG, 'Light persists after reload (even though the phone is dark)')
  await page.emulateMedia({ colorScheme: 'light' })
  await page.click('button[aria-label^="Settings"]')
  await page.click('[aria-label="Appearance"] button:has-text("Dark")')
  t = await themeState()
  ok(t.attr === 'dark' && t.bg === DARK_BG && t.saved === 'dark', 'choosing Dark overrides a light phone and is saved')
  await noOverflow('Settings (dark)')
  await page.screenshot({ path: `${S}/settings-dark.png` })
  await page.reload()
  await page.waitForSelector('.nav')
  t = await themeState()
  ok(t.attr === 'dark' && t.bg === DARK_BG, 'Dark persists after reload')
  await page.click('button[aria-label^="Settings"]')
  await page.click('[aria-label="Appearance"] button:has-text("System")')
  t = await themeState()
  ok(t.attr === 'light' && t.saved === 'system', 'back to System follows the (light) phone again')
  await page.click('button:has-text("Back")')

  // --- welcome splash ---
  const mk = () => browser.newContext({ viewport: { width: 390, height: 800 }, isMobile: true, hasTouch: true })
  let sctx = await mk()
  let sp = await sctx.newPage()
  await sp.goto(URL)
  await sp.waitForSelector('.hero')
  ok((await sp.locator('.splash').count()) === 0, 'splash: skipped in automated browsers by default')
  await sp.close()
  sp = await sctx.newPage()
  await sp.goto(`${URL}?splash=1`)
  await sp.waitForSelector('.splash')
  const splashText = await sp.innerText('.splash')
  ok(/Expenses/.test(splashText) && /Good (morning|afternoon|evening)/.test(splashText) && /safe to spend/i.test(splashText), `splash: shows the name, a greeting and the tagline (${splashText.replace(/\n+/g, ' | ')})`)
  await sp.waitForSelector('.splash', { state: 'detached', timeout: 4000 })
  ok(true, 'splash: dismisses itself')
  await sp.waitForSelector('.hero')
  await sp.goto(`${URL}?splash=1`)
  await sp.waitForSelector('.splash')
  await sp.click('.splash')
  await sp.waitForSelector('.splash', { state: 'detached', timeout: 1500 })
  ok(true, 'splash: tap to skip')
  await sctx.close()

  // --- Back button: close things first, then ask before exiting ---
  const bctx = await mk()
  const bp = await bctx.newPage()
  const bBody = (sel) => bp.innerText(sel).catch(() => '')
  const settle = () => bp.waitForTimeout(250)
  await bp.goto(URL)
  await bp.waitForSelector('.hero')
  await bp.goBack(); await settle()
  ok((await bp.locator('.dialog').count()) === 1 && /Exit Expenses\?/.test(await bBody('.dialog')), 'back: at Home, Back asks "Exit Expenses?" instead of closing')
  await bp.click('.dialog button:has-text("Stay")'); await settle()
  ok((await bp.locator('.dialog').count()) === 0 && (await bp.locator('.hero').count()) === 1, 'back: Stay keeps you in the app')
  await bp.goBack(); await settle()
  ok((await bp.locator('.dialog').count()) === 1, 'back: pressing Back again asks again')
  await bp.press('body', 'Escape'); await settle()
  ok((await bp.locator('.dialog').count()) === 0, 'back: Escape also means Stay')
  await bp.click('button[aria-label="Add entry"]'); await bp.waitForSelector('.sheet')
  await bp.goBack(); await settle()
  ok((await bp.locator('.sheet').count()) === 0 && (await bp.locator('.dialog').count()) === 0, 'back: closes an open sheet first (no exit prompt)')
  await bp.click('nav .nav-item:has-text("Insights")'); await bp.waitForSelector('h1:has-text("Insights")')
  await bp.goBack(); await settle()
  ok((await bp.locator('.hero').count()) === 1 && (await bp.locator('.dialog').count()) === 0, 'back: from another tab goes to Home (no exit prompt)')
  await bp.click('button[aria-label^="Settings"]'); await bp.click('.row-card:has-text("Categories")'); await bp.waitForSelector('h1:has-text("Categories")')
  await bp.goBack(); await settle()
  ok(/Settings/.test(await bBody('main')) && !/New expense category/.test(await bBody('main')), 'back: leaves a Settings sub-page for the Settings list')
  await bp.goBack(); await settle()
  ok((await bp.locator('.hero').count()) === 1 && (await bp.locator('.dialog').count()) === 0, 'back: then Settings -> Home')
  await bp.click('button[aria-label="Search the app"]'); await bp.waitForSelector('.palette')
  await bp.goBack(); await settle()
  ok((await bp.locator('.palette').count()) === 0 && (await bp.locator('.dialog').count()) === 0, 'back: closes the search panel first')
  await bp.goBack(); await settle()
  ok((await bp.locator('.dialog').count()) === 1, 'back: and only then asks to exit')
  await bp.click('.dialog button:has-text("Exit")')
  const left = await bp.waitForFunction(() => location.href === 'about:blank' || !!document.querySelector('.toast'), null, { timeout: 4000 }).then(() => true, () => false).catch(() => false)
  ok(left || bp.isClosed() || bp.url() === 'about:blank', `back: confirming Exit leaves the app (or, if the browser refuses, says to press Back once more) [url=${bp.isClosed() ? 'closed' : bp.url()}]`)
  await bctx.close()

  // --- "use it as an app": one-tap on Android, how-to on iPhone, help inside in-app browsers ---
  const UA = {
    android: 'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36',
    iphone: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
    facebook: 'Mozilla/5.0 (Linux; Android 14; Pixel 8; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.0.0 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/450.0.0.0;]',
  }
  const mkUA = (ua, extra = {}) => browser.newContext({ viewport: { width: 390, height: 800 }, isMobile: true, hasTouch: true, userAgent: ua, ...extra })
  const fireInstallEvent = (pg, outcome) => pg.evaluate((o) => {
    window.__log = []
    const e = new Event('beforeinstallprompt')
    e.prompt = () => { window.__log.push('prompt'); return Promise.resolve() }
    e.userChoice = Promise.resolve({ outcome: o })
    window.dispatchEvent(e)
  }, outcome)

  // Android: a real one-tap prompt
  let ictx = await mkUA(UA.android)
  let ip = await ictx.newPage()
  await ip.goto(`${URL}?install=1`)
  await ip.waitForSelector('.hero')
  await ip.waitForTimeout(2800)
  ok((await ip.locator('.install-banner').count()) === 0, 'install (Android): nothing is shown while the browser offers no install prompt')
  await fireInstallEvent(ip, 'accepted')
  await ip.waitForSelector('.install-banner', { timeout: 5000 })
  const bannerText = await ip.innerText('.install-banner')
  ok(/Install Expenses/.test(bannerText) && /One tap/.test(bannerText), `install (Android): banner offers one-tap install (${bannerText.replace(/\n+/g, ' | ')})`)
  const bb = await ip.locator('.install-banner').boundingBox()
  const nb = await ip.locator('.nav').boundingBox()
  ok(bb.y + bb.height <= nb.y && bb.x >= 0 && bb.x + bb.width <= 390, 'install: the banner sits above the tab bar and inside the screen')
  ok((await ip.evaluate(() => document.documentElement.scrollWidth <= innerWidth)), 'install: the banner causes no horizontal overflow')
  await ip.screenshot({ path: `${S}/install-banner.png` })
  await ip.click('.install-banner button:has-text("Install")')
  await ip.waitForSelector('.install-banner', { state: 'detached' })
  ok((await ip.evaluate(() => window.__log)).includes('prompt'), 'install (Android): tapping Install opens the browser\'s own install prompt')
  await ip.evaluate(() => window.dispatchEvent(new Event('appinstalled')))
  await ip.click('button[aria-label^="Settings"]')
  await ip.waitForSelector('text=Installed as an app')
  ok(true, 'install: Settings says "Installed as an app" once installed')
  await ictx.close()

  // Android: dismissing hides it for two weeks, but Settings and search still offer it
  ictx = await mkUA(UA.android)
  ip = await ictx.newPage()
  await ip.goto(`${URL}?install=1`)
  await ip.waitForSelector('.hero')
  await fireInstallEvent(ip, 'accepted')
  await ip.waitForSelector('.install-banner', { timeout: 5000 })
  await ip.click('.install-banner button[aria-label="Not now"]')
  await ip.waitForSelector('.install-banner', { state: 'detached' })
  await ip.reload()
  await ip.waitForSelector('.hero')
  await fireInstallEvent(ip, 'accepted')
  await ip.waitForTimeout(3000)
  ok((await ip.locator('.install-banner').count()) === 0, 'install: after "Not now" the banner stays away on the next visit')
  await ip.click('button[aria-label="Search the app"]')
  await ip.fill('.palette input', 'home screen')
  ok(/Install as an app/.test(await ip.locator('.palette [role=option]').first().innerText()), 'install: search finds "Install as an app" ("home screen")')
  await ip.press('.palette input', 'Escape')
  await ip.click('button[aria-label^="Settings"]')
  await ip.click('.row-card:has-text("Install as an app")')
  await ip.waitForFunction(() => (window.__log || []).includes('prompt'))
  ok(true, 'install: Settings > Install as an app still opens the prompt')
  await ictx.close()

  // iPhone: Apple offers no install button to websites, so show the three taps
  ictx = await mkUA(UA.iphone)
  ip = await ictx.newPage()
  await ip.goto(`${URL}?install=1`)
  await ip.waitForSelector('.install-banner', { timeout: 6000 })
  ok(/Use Expenses as an app/.test(await ip.innerText('.install-banner')) && /Show me how/.test(await ip.innerText('.install-banner')), 'install (iPhone): banner appears on its own and offers the how-to')
  await ip.click('.install-banner button:has-text("Show me how")')
  await ip.waitForSelector('.sheet')
  const guide = await ip.innerText('.sheet')
  ok(/Add Expenses to your Home Screen/.test(guide) && /Share/.test(guide) && /Add to Home Screen/.test(guide) && /Add\b/.test(guide), 'install (iPhone): the sheet shows Share -> Add to Home Screen -> Add')
  await ip.screenshot({ path: `${S}/install-guide-ios.png` })
  await ip.click('.sheet button:has-text("Got it")')
  await ip.waitForSelector('.sheet', { state: 'detached' })
  await ictx.close()

  // iPhone, already installed to the Home Screen: no banner
  ictx = await mkUA(UA.iphone)
  await ictx.addInitScript(() => Object.defineProperty(navigator, 'standalone', { get: () => true }))
  ip = await ictx.newPage()
  await ip.goto(`${URL}?install=1`)
  await ip.waitForSelector('.hero')
  await ip.waitForTimeout(3000)
  ok((await ip.locator('.install-banner').count()) === 0, 'install (iPhone): no banner once running from the Home Screen')
  await ictx.close()

  // Facebook / Messenger in-app browser: cannot install, so explain how to open the page properly
  ictx = await mkUA(UA.facebook, { permissions: ['clipboard-read', 'clipboard-write'] })
  ip = await ictx.newPage()
  await ip.goto(`${URL}?install=1`)
  await ip.waitForSelector('.install-banner', { timeout: 6000 })
  ok(/Open in your browser to install/.test(await ip.innerText('.install-banner')), 'install (in-app browser): banner says to open it in the real browser')
  await ip.click('.install-banner button:has-text("How")')
  await ip.waitForSelector('.sheet')
  ok(/Open in browser/.test(await ip.innerText('.sheet')) && /expense-tracker-/.test(await ip.innerText('.sheet')), 'install (in-app browser): the sheet explains the steps and shows the link')
  await ip.click('.sheet button:has-text("Copy link")')
  await ip.waitForSelector('.sheet button:has-text("Link copied")', { timeout: 3000 })
  ok(true, 'install (in-app browser): Copy link works')
  await ictx.close()

  // --- dark mode ---
  const dark = await browser.newContext({ viewport: { width: 390, height: 800 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: 'dark' })
  await dark.clock.setFixedTime(new Date(2026, 9, 18, 12, 0, 0))
  const dp = await dark.newPage()
  dp.on('dialog', (d) => d.accept())
  await dp.goto(URL)
  await dp.click('button[aria-label^="Settings"]')
  await dp.click('.row-card:has-text("Backup")')
  await dp.setInputFiles('input[type=file]', FIXTURE)
  await dp.waitForSelector('[role=status]')
  await dp.click('button:has-text("Back")')
  await dp.click('button:has-text("Back")')
  await dp.waitForSelector('.hero')
  const dcolor = (sel) => dp.locator(sel).first().evaluate((el) => getComputedStyle(el).color)
  ok((await dcolor('.trio .stat:has-text("Income") .money-in')) === 'rgb(74, 222, 128)' && (await dcolor('.trio .stat:has-text("Spent") .money-out')) === 'rgb(248, 113, 113)', 'dark theme: income light green, expense light red')
  await dp.screenshot({ path: `${S}/home-dark.png`, fullPage: true })
  await dp.click('nav .nav-item:has-text("Insights")')
  await dp.waitForSelector('svg.chart')
  await dp.screenshot({ path: `${S}/insights-dark.png`, fullPage: true })
  ok(true, 'dark mode renders (screenshots saved)')
  await dark.close()

  // --- offline, with bundled fonts ---
  await page.reload()
  await page.waitForSelector('.hero')
  await page.waitForTimeout(1500)
  await ctx.setOffline(true)
  await page.reload()
  await page.waitForSelector('.hero')
  ok((await page.locator('nav').count()) === 1, 'app loads offline')
  const fonts = await page.evaluate(async () => { await document.fonts.ready; return [...document.fonts].filter((f) => f.status === 'loaded').map((f) => f.family) })
  ok(fonts.some((f) => /Figtree/.test(f)) && fonts.some((f) => /Bricolage/.test(f)), `bundled fonts load offline (${[...new Set(fonts)].join(', ')})`)

  ok(errors.length === 0, `no console/page errors ${JSON.stringify(errors)}`)
  await browser.close()
  process.exit(failed ? 1 : 0)
})().catch((e) => { console.log('✗ CRASH', e.message); process.exit(1) })
